apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-vk-app
  labels:
    app: nagp-vk-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nagp-vk-app
  template:
    metadata:
      labels:
        app: nagp-vk-app
    spec:  
        containers:
        - name: tomcat
          image: dtr.nagarro.com:443/i-veerpalkaur-master
          ports:
          - containerPort: 8080
          
---
apiVersion: v1
kind: Service
metadata:
  name: nagp-service
spec:
  type: NodePort
  selector:
    app: nagp-vk-app
  ports:
  - name: port8080
    protocol: TCP
    nodePort: {{ .Values.nodePort }}
    port: 8080
    targetPort: 8080


  